on: push
name: User Service
jobs:

  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - run: go mod vendor
      - name: Lint
        run: sudo make lint
      - name: Unit Test
        run: make test-race
      - name: Build
        run: make build
      - name: Start containers
        run: make run
      - name: Test Integration
        run: make test-integration
