on: push
name: User Service
jobs:

  build:
    runs-on: ubuntu-latest
    name: Build
    services:
      # label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:10.5
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - run: go mod vendor
      - name: Lint
        run: sudo make lint
      - name: Unit Test
        run: make test-race
      - name: Build
        run: make build
      - name: Start containers
        run: make run
      - name: Test Integration
        run: make test-integration